// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3ztzcrkiUebyEOCJVX9yuTzWGioWUCAM',
    appId: '1:151395442234:web:cf0a2302551701a53b5f03',
    messagingSenderId: '151395442234',
    projectId: 'trustnet-ai',
    authDomain: 'trustnet-ai.firebaseapp.com',
    storageBucket: 'trustnet-ai.firebasestorage.app',
    measurementId: 'G-G4Z3V7E2S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuDYW4pJ38nyifBeVRr7PIWmlqEwu88-Y',
    appId: '1:151395442234:android:7c5f3af9f9ed53b43b5f03',
    messagingSenderId: '151395442234',
    projectId: 'trustnet-ai',
    storageBucket: 'trustnet-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVOkqPANHtTxvDV8mFTakGGOXz9K1oNkM',
    appId: '1:151395442234:ios:9e7ad87a12cde71c3b5f03',
    messagingSenderId: '151395442234',
    projectId: 'trustnet-ai',
    storageBucket: 'trustnet-ai.firebasestorage.app',
    iosBundleId: 'com.example.trustnetAiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVOkqPANHtTxvDV8mFTakGGOXz9K1oNkM',
    appId: '1:151395442234:ios:9e7ad87a12cde71c3b5f03',
    messagingSenderId: '151395442234',
    projectId: 'trustnet-ai',
    storageBucket: 'trustnet-ai.firebasestorage.app',
    iosBundleId: 'com.example.trustnetAiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3ztzcrkiUebyEOCJVX9yuTzWGioWUCAM',
    appId: '1:151395442234:web:cacc4b5058df9b423b5f03',
    messagingSenderId: '151395442234',
    projectId: 'trustnet-ai',
    authDomain: 'trustnet-ai.firebaseapp.com',
    storageBucket: 'trustnet-ai.firebasestorage.app',
    measurementId: 'G-3J684YS7FX',
  );
}
