import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/user_provider.dart';
import '../../widgets/app_layout.dart';

class AITrustReportScreen extends StatelessWidget {
  const AITrustReportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return AppLayout(
      role: 'transporter',
      child: Consumer<UserProvider>(
        builder: (context, userProvider, child) {
          final user = userProvider.user;
          final trustScore = user?.trustScore ?? 0.0;
          final aiReportText = user?.aiReport ?? "";

          // Determine theme based on trust score
          Color themeColor;
          IconData headerIcon;
          String statusText;

          if (trustScore >= 80) {
            themeColor = Colors.green;
            headerIcon = Icons.verified;
            statusText = "Excellent Reliability";
          } else if (trustScore >= 50) {
            themeColor = Colors.orange;
            headerIcon = Icons.warning_amber_rounded;
            statusText = "Needs Improvement";
          } else {
            themeColor = Colors.red;
            headerIcon = Icons.gpp_bad;
            statusText = "High Risk";
          }

          final isGenerating = aiReportText.isEmpty && trustScore > 0;

          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Text(
                  'AI Trust Report',
                  style: TextStyle(fontSize: 28, fontWeight: FontWeight.bold, color: Color(0xFF0F172A)),
                ),
                const Text(
                  'Generated by Gemini Intelligence',
                  style: TextStyle(fontSize: 14, color: Colors.purple, fontWeight: FontWeight.w500),
                ),
                const SizedBox(height: 24),

                // Overall Status Card
                Card(
                  elevation: 0,
                  color: themeColor.withValues(alpha: 0.1),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(16),
                    side: BorderSide(color: themeColor.withValues(alpha: 0.3)),
                  ),
                  child: Padding(
                    padding: const EdgeInsets.all(20),
                    child: Row(
                      children: [
                        Container(
                          padding: const EdgeInsets.all(12),
                          decoration: BoxDecoration(
                            color: themeColor.withValues(alpha: 0.2),
                            shape: BoxShape.circle,
                          ),
                          child: Icon(headerIcon, color: themeColor, size: 32),
                        ),
                        const SizedBox(width: 16),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(
                                statusText,
                                style: TextStyle(
                                  fontSize: 20,
                                  fontWeight: FontWeight.bold,
                                  color: themeColor.withValues(alpha: 0.9),
                                ),
                              ),
                              Text(
                                'Trust Score: ${trustScore.toStringAsFixed(0)}',
                                style: const TextStyle(fontSize: 16, color: Colors.black87),
                              ),
                            ],
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
                const SizedBox(height: 24),

                // AI Report Content
                if (isGenerating)
                  Center(
                    child: Padding(
                      padding: const EdgeInsets.all(32),
                      child: Column(
                        children: [
                          const CircularProgressIndicator(color: Colors.purple),
                          const SizedBox(height: 16),
                          Text(
                            'Gemini is analyzing your latest performance...',
                            style: TextStyle(color: Colors.purple.shade300, fontStyle: FontStyle.italic),
                          ),
                        ],
                      ),
                    ),
                  )
                else if (aiReportText.isEmpty)
                  Center(
                    child: Padding(
                      padding: const EdgeInsets.all(32),
                      child: Column(
                        children: [
                          Icon(Icons.description_outlined, size: 48, color: Colors.grey.shade400),
                          const SizedBox(height: 16),
                          const Text(
                            'No report generated yet.',
                            style: TextStyle(color: Colors.black54),
                          ),
                        ],
                      ),
                    ),
                  )
                else
                  _buildParsedReport(aiReportText),
              ],
            ),
          );
        },
      ),
    );
  }

  Widget _buildParsedReport(String aiReportText) {
    // Simple parser for the expected sections
    String summary = "";
    String strengths = "";
    String risks = "";
    String recommendation = "";

    // Split by common numbering or headings Gemini might output
    // A more robust approach searches for keywords
    final sections = aiReportText.split(RegExp(r'(?=\d\.)|(?=\*\*\d\.)'));

    for (var section in sections) {
      final s = section.trim();
      if (s.isEmpty) continue;
      
      final lower = s.toLowerCase();
      if (lower.contains('overall summary')) {
        summary = s;
      } else if (lower.contains('strengths')) {
        strengths = s;
      } else if (lower.contains('risks') || lower.contains('concerns')) {
        risks = s;
      } else if (lower.contains('recommendation')) {
        recommendation = s;
      }
    }

    // Fallback if parsing fails (Gemini format changes)
    if (summary.isEmpty && strengths.isEmpty && risks.isEmpty && recommendation.isEmpty) {
      return Card(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: BorderSide(color: Colors.grey.shade200),
        ),
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Text(aiReportText, style: const TextStyle(height: 1.5)),
        ),
      );
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (summary.isNotEmpty) _buildSectionCard("Overall Summary", summary, Icons.analytics, Colors.blue),
        if (strengths.isNotEmpty) _buildSectionCard("Strengths", strengths, Icons.thumb_up, Colors.green),
        if (risks.isNotEmpty) _buildSectionCard("Risks or Concerns", risks, Icons.warning_amber, Colors.orange),
        if (recommendation.isNotEmpty) _buildSectionCard("Recommendation", recommendation, Icons.lightbulb_outline, Colors.purple),
      ],
    );
  }

  Widget _buildSectionCard(String title, String content, IconData icon, Color color) {
    // Clean up content by removing the "1. Overall summary:" part if present
    final lines = content.split('\n');
    if (lines.isNotEmpty && (lines[0].contains('1.') || lines[0].contains('2.') || lines[0].contains('3.') || lines[0].contains('4.'))) {
      lines.removeAt(0);
    }
    final cleanContent = lines.join('\n').trim();

    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Card(
        elevation: 0,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: BorderSide(color: Colors.grey.shade200),
        ),
        child: Padding(
          padding: const EdgeInsets.all(20),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Icon(icon, color: color, size: 24),
                  const SizedBox(width: 12),
                  Text(
                    title,
                    style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Text(
                cleanContent,
                style: const TextStyle(fontSize: 15, color: Colors.black87, height: 1.5),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
